import type { PhotoLayout, Machine } from '@/types';

export const MOCK_LAYOUTS: PhotoLayout[] = [
  {
    id: 'layout-2x2',
    name: '2x2 Classic',
    type: '2x2',
    photoCount: 4,
    thumbnailUrl: '/layouts/2x2.png',
    price: 100,
    visible: true,
    template: {
      backgroundColor: '#ffffff',
      borderColor: '#000000',
      borderWidth: 2,
      photoShape: 'square',
      photoSize: 200,
      logoPosition: 'bottom-right',
      fontFamily: 'Inter',
      textColor: '#000000',
    },
  },
  {
    id: 'layout-3x3',
    name: '3x3 Grid',
    type: '3x3',
    photoCount: 9,
    thumbnailUrl: '/layouts/3x3.png',
    price: 150,
    visible: true,
    template: {
      backgroundColor: '#f0f0f0',
      borderColor: '#333333',
      borderWidth: 3,
      photoShape: 'rounded',
      photoSize: 180,
      logoPosition: 'top-right',
      fontFamily: 'Poppins',
      textColor: '#333333',
    },
  },
  {
    id: 'layout-strip',
    name: 'Photo Strip',
    type: 'strip',
    photoCount: 4,
    thumbnailUrl: '/layouts/strip.png',
    price: 80,
    visible: true,
    template: {
      backgroundColor: '#ffffff',
      borderColor: '#000000',
      borderWidth: 1,
      photoShape: 'square',
      photoSize: 150,
      logoPosition: 'bottom-left',
      fontFamily: 'Inter',
      textColor: '#000000',
    },
  },
  {
    id: 'layout-single',
    name: 'Single Portrait',
    type: 'single',
    photoCount: 1,
    thumbnailUrl: '/layouts/single.png',
    price: 50,
    visible: true,
    template: {
      backgroundColor: '#ffffff',
      borderColor: '#gold',
      borderWidth: 5,
      photoShape: 'rounded',
      photoSize: 400,
      logoPosition: 'center',
      fontFamily: 'Poppins',
      textColor: '#gold',
    },
  },
];

export const MOCK_MACHINES: Machine[] = [
  {
    id: 'machine-001',
    name: 'Mall Kiosk #1',
    status: 'ONLINE',
    mode: 'NORMAL',
    location: 'City Center Mall, Floor 2',
    lastSync: Date.now() - 60000,
    printStats: {
      totalPrints: 1247,
      eventPrints: 0,
      normalPrints: 1247,
      lastPrintTime: Date.now() - 300000,
      paperRemaining: 75,
    },
    health: {
      paperLevel: 75,
      inkLevel: 60,
      temperature: 35,
      errors: [],
    },
  },
  {
    id: 'machine-002',
    name: 'Wedding Venue #1',
    status: 'ONLINE',
    mode: 'EVENT',
    location: 'Grand Ballroom, Downtown',
    lastSync: Date.now() - 30000,
    printStats: {
      totalPrints: 543,
      eventPrints: 543,
      normalPrints: 0,
      lastPrintTime: Date.now() - 120000,
      paperRemaining: 45,
    },
    health: {
      paperLevel: 45,
      inkLevel: 50,
      temperature: 38,
      errors: [],
    },
  },
  {
    id: 'machine-003',
    name: 'Airport Terminal',
    status: 'OFFLINE',
    mode: 'NORMAL',
    location: 'Terminal 3, Gate 12',
    lastSync: Date.now() - 3600000,
    printStats: {
      totalPrints: 892,
      eventPrints: 0,
      normalPrints: 892,
      lastPrintTime: Date.now() - 3600000,
      paperRemaining: 20,
    },
    health: {
      paperLevel: 20,
      inkLevel: 15,
      temperature: 42,
      errors: ['Low paper', 'Low ink'],
    },
  },
];
